on:
  push:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: nickbenedetti/gha-composite@1.1.5
        with:
          who-to-greet: ${${{ github.repository }}#*/}
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
